/** *****************************************************************************
 * Licensed Materials - Property of IBM
 * (c) Copyright IBM Corporation 2019. All Rights Reserved.
 *
 * Note to U.S. Government Users Restricted Rights:
 * Use, duplication or disclosure restricted by GSA ADP Schedule
 * Contract with IBM Corp.
 ****************************************************************************** */

export const policiesTestingDataSet1 = [
  {
    'metadata':{
      'name':'compliance-all',
      'namespace':'mcm',
      'selfLink':'/apis/compliance.mcm.ibm.com/v1alpha1/namespaces/mcm/compliances/compliance-all',
      'annotations':{
        'seed-generation':'1'
      },
      'resourceVersion':'1071070',
      '__typename':'Metadata'
    },
    'name':'compliance-all',
    'namespace':'mcm',
    'raw':{
      'apiVersion':'compliance.mcm.ibm.com/v1alpha1',
      'kind':'Compliance',
      'metadata':{
        'annotations':{
          'seed-generation':'1'
        },
        'creationTimestamp':'2019-05-21T14:02:49Z',
        'finalizers':[
          'propagator.finalizer.mcm.ibm.com'
        ],
        'generation':6,
        'name':'compliance-all',
        'namespace':'mcm',
        'resourceVersion':'1071070',
        'selfLink':'/apis/compliance.mcm.ibm.com/v1alpha1/namespaces/mcm/compliances/compliance-all',
        'uid':'1e04ec63-7bd1-11e9-820c-005056a061f1'
      },
      'spec':{
        'runtime-rules':[
          {
            'apiVersion':'policy.mcm.ibm.com/v1alpha1',
            'kind':'Policy',
            'metadata':{
              'creationTimestamp':null,
              'labels':{
                'cis-docker':'true'
              },
              'name':'policy-comp'
            },
            'spec':{
              'complianceType':'musthave',
              'namespaces':{
                'exclude':[
                  'kube*'
                ],
                'include':[
                  'default'
                ]
              },
              'object-templates':[
                {
                  'complianceType':'musthave',
                  'objectDefinition':{
                    'apiVersion':'rbac.authorization.k8s.io/v1',
                    'kind':'RoleBinding',
                    'metadata':{
                      'name':'operate-pods-rolebinding',
                      'namespace':'default'
                    },
                    'roleRef':{
                      'apiGroup':'rbac.authorization.k8s.io',
                      'kind':'Role',
                      'name':'operator'
                    },
                    'subjects':[
                      {
                        'apiGroup':'rbac.authorization.k8s.io',
                        'kind':'User',
                        'name':'admin'
                      }
                    ]
                  },
                  'status':{
                    'Validity':{

                    }
                  }
                },
                {
                  'complianceType':'musthave',
                  'objectDefinition':{
                    'apiVersion':'policy/v1beta1',
                    'kind':'PodSecurityPolicy',
                    'metadata':{
                      'annotations':{
                        'seccomp.security.alpha.kubernetes.io/allowedProfileNames':'*'
                      },
                      'name':'restricted-mcm'
                    },
                    'spec':{
                      'allowPrivilegeEscalation':false,
                      'allowedCapabilities':[
                        '*'
                      ],
                      'fsGroup':{
                        'rule':'RunAsAny'
                      },
                      'hostIPC':false,
                      'hostNetwork':true,
                      'hostPID':false,
                      'hostPorts':[
                        {
                          'max':65535,
                          'min':1000
                        }
                      ],
                      'privileged':false,
                      'runAsUser':{
                        'rule':'RunAsAny'
                      },
                      'seLinux':{
                        'rule':'RunAsAny'
                      },
                      'supplementalGroups':{
                        'rule':'RunAsAny'
                      },
                      'volumes':[
                        '*'
                      ]
                    }
                  },
                  'status':{
                    'Validity':{

                    }
                  }
                },
                {
                  'complianceType':'musthave',
                  'objectDefinition':{
                    'apiVersion':'networking.k8s.io/v1',
                    'kind':'NetworkPolicy',
                    'metadata':{
                      'name':'deny-from-other-namespaces',
                      'namespace':'default'
                    },
                    'spec':{
                      'ingress':[
                        {
                          'from':[
                            {
                              'podSelector':{

                              }
                            }
                          ]
                        }
                      ],
                      'podSelector':{
                        'matchLabels':null
                      }
                    }
                  },
                  'status':{
                    'Validity':{

                    }
                  }
                },
                {
                  'complianceType':'musthave',
                  'objectDefinition':{
                    'apiVersion':'v1',
                    'kind':'LimitRange',
                    'metadata':{
                      'name':'mem-limit-range'
                    },
                    'spec':{
                      'limits':[
                        {
                          'default':{
                            'memory':'512Mi'
                          },
                          'defaultRequest':{
                            'memory':'256Mi'
                          },
                          'type':'Container'
                        }
                      ]
                    }
                  },
                  'status':{
                    'Validity':{

                    }
                  }
                }
              ],
              'remediationAction':'inform',
              'role-templates':[
                {
                  'apiVersion':'roletemplate.mcm.ibm.com/v1alpha1',
                  'complianceType':'musthave',
                  'metadata':{
                    'creationTimestamp':null,
                    'name':'operator-role'
                  },
                  'rules':[
                    {
                      'complianceType':'mustnothave',
                      'policyRule':{
                        'apiGroups':[
                          'core'
                        ],
                        'resources':[
                          'secrets'
                        ],
                        'verbs':[
                          'get',
                          'list',
                          'watch',
                          'delete',
                          'create',
                          'update',
                          'patch'
                        ]
                      }
                    },
                    {
                      'complianceType':'musthave',
                      'policyRule':{
                        'apiGroups':[
                          'core'
                        ],
                        'resources':[
                          'pods'
                        ],
                        'verbs':[
                          'get',
                          'list',
                          'watch'
                        ]
                      }
                    }
                  ],
                  'selector':{
                    'matchLabels':{
                      'dev':'true'
                    }
                  },
                  'status':{
                    'Validity':{

                    }
                  }
                }
              ]
            },
            'status':{

            }
          }
        ]
      },
      'status':{
        'placementBindings':[
          'binding-comp'
        ],
        'placementPolicies':[
          'placement-comp'
        ],
        'status':{
          'cluster1':{
            'aggregatePoliciesStatus':{
              'policy-comp':{
                'compliant':'NonCompliant',
                'valid':true
              }
            },
            'clustername':'cluster1',
            'compliant':'NonCompliant'
          },
          'clusterhub':{
            'aggregatePoliciesStatus':{
              'policy-comp':{
                'compliant':'NonCompliant',
                'valid':true
              }
            },
            'clustername':'clusterhub',
            'compliant':'NonCompliant'
          }
        }
      }
    },
    'remediation':'',
    'policyCompliant':'2/2',
    'clusterCompliant':'2/2',
    'placementPolicies':[
      {
        'metadata':{
          'name':'placement-comp',
          'selfLink':'/apis/mcm.ibm.com/v1alpha1/namespaces/mcm/placementpolicies/placement-comp',
          '__typename':'Metadata'
        },
        '__typename':'PlacementPolicy'
      }
    ],
    'placementBindings':[
      {
        'metadata':{
          'name':'binding-comp',
          'selfLink':'/apis/mcm.ibm.com/v1alpha1/namespaces/mcm/placementbindings/binding-comp',
          '__typename':'Metadata'
        },
        '__typename':'PlacementBinding'
      }
    ],
    '__typename':'Compliance'
  },
  {
    'metadata':{
      'name':'policy-ma',
      'namespace':'mcm',
      'selfLink':'/apis/policy.mcm.ibm.com/v1alpha1/namespaces/mcm/policies/policy-ma',
      'annotations':{
        'policy.mcm.ibm.com/categories':'SystemAndInformationIntegrity',
        'policy.mcm.ibm.com/controls':'MutationAdvisor',
        'policy.mcm.ibm.com/standards':'NIST',
        'seed-generation':'1'
      },
      'resourceVersion':'1308515',
      '__typename':'Metadata'
    },
    'name':'policy-ma',
    'namespace':'mcm',
    'raw':{
      'apiVersion':'policy.mcm.ibm.com/v1alpha1',
      'kind':'Policy',
      'metadata':{
        'annotations':{
          'policy.mcm.ibm.com/categories':'SystemAndInformationIntegrity',
          'policy.mcm.ibm.com/controls':'MutationAdvisor',
          'policy.mcm.ibm.com/standards':'NIST',
          'seed-generation':'1'
        },
        'creationTimestamp':'2019-05-17T12:58:05Z',
        'finalizers':[
          'propagator.finalizer.mcm.ibm.com'
        ],
        'generation':22,
        'name':'policy-ma',
        'namespace':'mcm',
        'resourceVersion':'1308515',
        'selfLink':'/apis/policy.mcm.ibm.com/v1alpha1/namespaces/mcm/policies/policy-ma',
        'uid':'692d81a1-78a3-11e9-820c-005056a061f1'
      },
      'spec':{
        'namespaces':{

        },
        'policy-templates':[
          {
            'objectDefinition':{
              'apiVersion':'policies.ibm.com/v1alpha1',
              'kind':'MutationPolicy',
              'metadata':{
                'label':{
                  'category':'System-Integrity'
                },
                'name':'mutation-policy-example'
              },
              'spec':{
                'conditions':{
                  'ownership':[
                    'ReplicaSet',
                    'Deployment',
                    'DeamonSet',
                    'ReplicationController'
                  ]
                },
                'namespaceSelector':{
                  'exclude':[
                    'kube-system'
                  ],
                  'include':[
                    'default',
                    'kube-*'
                  ]
                },
                'remediationAction':'enforce'
              }
            },
            'status':{
              'Validity':{

              }
            }
          }
        ],
        'remediationAction':'enforce'
      },
      'status':{
        'placementBindings':[
          'binding-ma'
        ],
        'placementPolicies':[
          'placement-ma'
        ],
        'status':{
          'cluster1':{
            'aggregatePoliciesStatus':{
              'policy-ma':{
                'compliant':'NonCompliant'
              }
            },
            'clustername':'cluster1',
            'compliant':'NonCompliant'
          },
          'clusterhub':{
            'aggregatePoliciesStatus':{
              'policy-ma':{
                'compliant':'Compliant'
              }
            },
            'clustername':'clusterhub',
            'compliant':'Compliant'
          }
        }
      }
    },
    'remediation':'enforce',
    'policyCompliant':'1/2',
    'clusterCompliant':'1/2',
    'placementPolicies':[
      {
        'metadata':{
          'name':'placement-ma',
          'selfLink':'/apis/mcm.ibm.com/v1alpha1/namespaces/mcm/placementpolicies/placement-ma',
          '__typename':'Metadata'
        },
        '__typename':'PlacementPolicy'
      }
    ],
    'placementBindings':[
      {
        'metadata':{
          'name':'binding-ma',
          'selfLink':'/apis/mcm.ibm.com/v1alpha1/namespaces/mcm/placementbindings/binding-ma',
          '__typename':'Metadata'
        },
        '__typename':'PlacementBinding'
      }
    ],
    '__typename':'Compliance'
  },
  {
    'metadata':{
      'name':'policy-pod',
      'namespace':'mcm',
      'selfLink':'/apis/policy.mcm.ibm.com/v1alpha1/namespaces/mcm/policies/policy-pod',
      'annotations':{
        'policy.mcm.ibm.com/categories':'SystemAndCommunicationsProtections,SystemAndInformationIntegrity',
        'policy.mcm.ibm.com/controls':'MutationAdvisor,VA',
        'policy.mcm.ibm.com/standards':'NIST,HIPAA',
        'seed-generation':'1'
      },
      'resourceVersion':'131792',
      '__typename':'Metadata'
    },
    'name':'policy-pod',
    'namespace':'mcm',
    'raw':{
      'apiVersion':'policy.mcm.ibm.com/v1alpha1',
      'kind':'Policy',
      'metadata':{
        'annotations':{
          'policy.mcm.ibm.com/categories':'SystemAndCommunicationsProtections,SystemAndInformationIntegrity',
          'policy.mcm.ibm.com/controls':'MutationAdvisor,VA',
          'policy.mcm.ibm.com/standards':'NIST,HIPAA',
          'seed-generation':'1'
        },
        'creationTimestamp':'2019-05-17T12:57:48Z',
        'finalizers':[
          'propagator.finalizer.mcm.ibm.com'
        ],
        'generation':7,
        'name':'policy-pod',
        'namespace':'mcm',
        'resourceVersion':'131792',
        'selfLink':'/apis/policy.mcm.ibm.com/v1alpha1/namespaces/mcm/policies/policy-pod',
        'uid':'5f3aea80-78a3-11e9-820c-005056a061f1'
      },
      'spec':{
        'complianceType':'musthave',
        'namespaces':{
          'exclude':[
            'kube*'
          ],
          'include':[
            'default'
          ]
        },
        'object-templates':[
          {
            'complianceType':'musthave',
            'objectDefinition':{
              'apiVersion':'v1',
              'kind':'Pod',
              'metadata':{
                'name':'nginx-pod'
              },
              'spec':{
                'containers':[
                  {
                    'image':'nginx:1.7.9',
                    'name':'nginx',
                    'ports':[
                      {
                        'containerPort':80
                      }
                    ]
                  }
                ]
              }
            },
            'status':{
              'Validity':{

              }
            }
          }
        ],
        'remediationAction':'inform'
      },
      'status':{
        'placementBindings':[
          'binding-pod'
        ],
        'placementPolicies':[
          'placement-pod'
        ],
        'status':{
          'cluster1':{
            'aggregatePoliciesStatus':{
              'policy-pod':{
                'compliant':'NonCompliant'
              }
            },
            'clustername':'cluster1',
            'compliant':'NonCompliant'
          },
          'clusterhub':{
            'aggregatePoliciesStatus':{
              'policy-pod':{
                'compliant':'NonCompliant'
              }
            },
            'clustername':'clusterhub',
            'compliant':'NonCompliant'
          }
        }
      }
    },
    'remediation':'inform',
    'policyCompliant':'2/2',
    'clusterCompliant':'2/2',
    'placementPolicies':[
      {
        'metadata':{
          'name':'placement-pod',
          'selfLink':'/apis/mcm.ibm.com/v1alpha1/namespaces/mcm/placementpolicies/placement-pod',
          '__typename':'Metadata'
        },
        '__typename':'PlacementPolicy'
      }
    ],
    'placementBindings':[
      {
        'metadata':{
          'name':'binding-pod',
          'selfLink':'/apis/mcm.ibm.com/v1alpha1/namespaces/mcm/placementbindings/binding-pod',
          '__typename':'Metadata'
        },
        '__typename':'PlacementBinding'
      }
    ],
    '__typename':'Compliance'
  },
]

export const policiesTestingDataSet2 = [
  {
    'metadata':{
      'name':'1558374675051-policy-pod',
      'namespace':'mcm',
      'selfLink':'/apis/policy.mcm.ibm.com/v1alpha1/namespaces/mcm/policies/1558374675051-policy-pod',
      'annotations':{
        'policy.mcm.ibm.com/categories':'SystemAndCommunicationsProtections,SystemAndInformationIntegrity',
        'policy.mcm.ibm.com/controls':'MutationAdvisor,VA',
        'policy.mcm.ibm.com/standards':'NIST',
        'seed-generation':'2'
      },
      'resourceVersion':'6281988',
      '__typename':'Metadata'
    },
    'name':'1558374675051-policy-pod',
    'namespace':'mcm',
    'raw':{
      'apiVersion':'policy.mcm.ibm.com/v1alpha1',
      'kind':'Policy',
      'metadata':{
        'annotations':{
          'policy.mcm.ibm.com/categories':'SystemAndCommunicationsProtections,SystemAndInformationIntegrity',
          'policy.mcm.ibm.com/controls':'MutationAdvisor,VA',
          'policy.mcm.ibm.com/standards':'NIST',
          'seed-generation':'2'
        },
        'creationTimestamp':'2019-05-20T17:51:38Z',
        'finalizers':[
          'propagator.finalizer.mcm.ibm.com'
        ],
        'generation':6,
        'name':'1558374675051-policy-pod',
        'namespace':'mcm',
        'resourceVersion':'6281988',
        'selfLink':'/apis/policy.mcm.ibm.com/v1alpha1/namespaces/mcm/policies/1558374675051-policy-pod',
        'uid':'eacbfd03-7b27-11e9-a751-005056a0b88e'
      },
      'spec':{
        'complianceType':'musthave',
        'namespaces':{
          'exclude':[
            'kube*'
          ],
          'include':[
            'default'
          ]
        },
        'object-templates':[
          {
            'complianceType':'musthave',
            'objectDefinition':{
              'apiVersion':'v1',
              'kind':'Pod',
              'metadata':{
                'name':'nginx1'
              },
              'spec':{
                'containers':[
                  {
                    'image':'nginx:1.7.9',
                    'name':'nginx',
                    'ports':[
                      {
                        'containerPort':80
                      }
                    ]
                  }
                ]
              }
            },
            'status':{
              'Validity':{

              }
            }
          }
        ],
        'remediationAction':'inform'
      },
      'status':{
        'placementBindings':[
          '1558374675051-placement-binding-test'
        ],
        'placementPolicies':[
          '1558374675051-placement-policy-test'
        ],
        'status':{
          'cluster1':{
            'aggregatePoliciesStatus':{
              '1558374675051-policy-pod':{
                'compliant':'NonCompliant'
              }
            },
            'clustername':'cluster1',
            'compliant':'NonCompliant'
          },
          'clusterhub':{
            'aggregatePoliciesStatus':{
              '1558374675051-policy-pod':{
                'compliant':'NonCompliant'
              }
            },
            'clustername':'clusterhub',
            'compliant':'NonCompliant'
          }
        }
      }
    },
    'remediation':'inform',
    'policyCompliant':'2/2',
    'clusterCompliant':'2/2',
    'placementPolicies':[
      {
        'metadata':{
          'name':'1558374675051-placement-policy-test',
          'selfLink':'/apis/mcm.ibm.com/v1alpha1/namespaces/mcm/placementpolicies/1558374675051-placement-policy-test',
          '__typename':'Metadata'
        },
        '__typename':'PlacementPolicy'
      }
    ],
    'placementBindings':[
      {
        'metadata':{
          'name':'1558374675051-placement-binding-test',
          'selfLink':'/apis/mcm.ibm.com/v1alpha1/namespaces/mcm/placementbindings/1558374675051-placement-binding-test',
          '__typename':'Metadata'
        },
        '__typename':'PlacementBinding'
      }
    ],
    '__typename':'Compliance'
  },
  {
    'metadata':{
      'name':'1558382034240-policy-pod',
      'namespace':'mcm',
      'selfLink':'/apis/policy.mcm.ibm.com/v1alpha1/namespaces/mcm/policies/1558382034240-policy-pod',
      'annotations':{
        'policy.mcm.ibm.com/categories':'SystemAndCommunicationsProtections,SystemAndInformationIntegrity',
        'policy.mcm.ibm.com/controls':'MutationAdvisor,VA',
        'policy.mcm.ibm.com/standards':'NIST',
        'seed-generation':'2'
      },
      'resourceVersion':'6975805',
      '__typename':'Metadata'
    },
    'name':'1558382034240-policy-pod',
    'namespace':'mcm',
    'raw':{
      'apiVersion':'policy.mcm.ibm.com/v1alpha1',
      'kind':'Policy',
      'metadata':{
        'annotations':{
          'policy.mcm.ibm.com/categories':'SystemAndCommunicationsProtections,SystemAndInformationIntegrity',
          'policy.mcm.ibm.com/controls':'MutationAdvisor,VA',
          'policy.mcm.ibm.com/standards':'NIST',
          'seed-generation':'2'
        },
        'creationTimestamp':'2019-05-20T19:54:18Z',
        'finalizers':[
          'propagator.finalizer.mcm.ibm.com'
        ],
        'generation':11,
        'name':'1558382034240-policy-pod',
        'namespace':'mcm',
        'resourceVersion':'6975805',
        'selfLink':'/apis/policy.mcm.ibm.com/v1alpha1/namespaces/mcm/policies/1558382034240-policy-pod',
        'uid':'0d98fa74-7b39-11e9-a751-005056a0b88e'
      },
      'spec':{
        'complianceType':'musthave',
        'namespaces':{
          'exclude':[
            'kube*'
          ],
          'include':[
            'default'
          ]
        },
        'object-templates':[
          {
            'complianceType':'musthave',
            'objectDefinition':{
              'apiVersion':'v1',
              'kind':'Pod',
              'metadata':{
                'name':'nginx1'
              },
              'spec':{
                'containers':[
                  {
                    'image':'nginx:1.7.9',
                    'name':'nginx',
                    'ports':[
                      {
                        'containerPort':80
                      }
                    ]
                  }
                ]
              }
            },
            'status':{
              'Validity':{

              }
            }
          }
        ],
        'remediationAction':'inform'
      },
      'status':{
        'placementBindings':[
          '1558382034240-placement-binding-test'
        ],
        'placementPolicies':[
          '1558382034240-placement-policy-test'
        ],
        'status':{
          'cluster1':{
            'aggregatePoliciesStatus':{
              '1558382034240-policy-pod':{
                'compliant':'NonCompliant'
              }
            },
            'clustername':'cluster1',
            'compliant':'NonCompliant'
          },
          'clusterhub':{
            'aggregatePoliciesStatus':{
              '1558382034240-policy-pod':{
                'compliant':'NonCompliant'
              }
            },
            'clustername':'clusterhub',
            'compliant':'NonCompliant'
          }
        }
      }
    },
    'remediation':'inform',
    'policyCompliant':'2/2',
    'clusterCompliant':'2/2',
    'placementPolicies':[
      {
        'metadata':{
          'name':'1558382034240-placement-policy-test',
          'selfLink':'/apis/mcm.ibm.com/v1alpha1/namespaces/mcm/placementpolicies/1558382034240-placement-policy-test',
          '__typename':'Metadata'
        },
        '__typename':'PlacementPolicy'
      }
    ],
    'placementBindings':[
      {
        'metadata':{
          'name':'1558382034240-placement-binding-test',
          'selfLink':'/apis/mcm.ibm.com/v1alpha1/namespaces/mcm/placementbindings/1558382034240-placement-binding-test',
          '__typename':'Metadata'
        },
        '__typename':'PlacementBinding'
      }
    ],
    '__typename':'Compliance'
  },
  {
    'metadata':{
      'name':'policy-ma',
      'namespace':'mcm',
      'selfLink':'/apis/policy.mcm.ibm.com/v1alpha1/namespaces/mcm/policies/policy-ma',
      'annotations':{
        'policy.mcm.ibm.com/categories':'SystemAndInformationIntegrity',
        'policy.mcm.ibm.com/controls':'MutationAdvisor',
        'policy.mcm.ibm.com/standards':'NIST',
        'seed-generation':'1'
      },
      'resourceVersion':'6975864',
      '__typename':'Metadata'
    },
    'name':'policy-ma',
    'namespace':'mcm',
    'raw':{
      'apiVersion':'policy.mcm.ibm.com/v1alpha1',
      'kind':'Policy',
      'metadata':{
        'annotations':{
          'policy.mcm.ibm.com/categories':'SystemAndInformationIntegrity',
          'policy.mcm.ibm.com/controls':'MutationAdvisor',
          'policy.mcm.ibm.com/standards':'NIST',
          'seed-generation':'1'
        },
        'creationTimestamp':'2019-05-16T15:21:53Z',
        'finalizers':[
          'propagator.finalizer.mcm.ibm.com'
        ],
        'generation':48,
        'name':'policy-ma',
        'namespace':'mcm',
        'resourceVersion':'6975864',
        'selfLink':'/apis/policy.mcm.ibm.com/v1alpha1/namespaces/mcm/policies/policy-ma',
        'uid':'55ca144d-77ee-11e9-a751-005056a0b88e'
      },
      'spec':{
        'namespaces':{

        },
        'policy-templates':[
          {
            'objectDefinition':{
              'apiVersion':'policies.ibm.com/v1alpha1',
              'kind':'MutationPolicy',
              'metadata':{
                'label':{
                  'category':'System-Integrity'
                },
                'name':'mutation-policy-example'
              },
              'spec':{
                'conditions':{
                  'ownership':[
                    'ReplicaSet',
                    'Deployment',
                    'DeamonSet',
                    'ReplicationController'
                  ]
                },
                'namespaceSelector':{
                  'exclude':[
                    'kube-system'
                  ],
                  'include':[
                    'default',
                    'kube-*'
                  ]
                },
                'remediationAction':'enforce'
              }
            },
            'status':{
              'Validity':{

              }
            }
          }
        ],
        'remediationAction':'enforce'
      },
      'status':{
        'placementBindings':[
          'binding-ma'
        ],
        'placementPolicies':[
          'placement-ma'
        ],
        'status':{
          'cluster1':{
            'aggregatePoliciesStatus':{
              'policy-ma':{
                'compliant':'Compliant'
              }
            },
            'clustername':'cluster1',
            'compliant':'Compliant'
          },
          'clusterhub':{
            'aggregatePoliciesStatus':{
              'policy-ma':{
                'compliant':'Compliant'
              }
            },
            'clustername':'clusterhub',
            'compliant':'Compliant'
          }
        }
      }
    },
    'remediation':'enforce',
    'policyCompliant':'0/2',
    'clusterCompliant':'0/2',
    'placementPolicies':[
      {
        'metadata':{
          'name':'placement-ma',
          'selfLink':'/apis/mcm.ibm.com/v1alpha1/namespaces/mcm/placementpolicies/placement-ma',
          '__typename':'Metadata'
        },
        '__typename':'PlacementPolicy'
      }
    ],
    'placementBindings':[
      {
        'metadata':{
          'name':'binding-ma',
          'selfLink':'/apis/mcm.ibm.com/v1alpha1/namespaces/mcm/placementbindings/binding-ma',
          '__typename':'Metadata'
        },
        '__typename':'PlacementBinding'
      }
    ],
    '__typename':'Compliance'
  },
  {
    'metadata':{
      'name':'policy-pod',
      'namespace':'mcm',
      'selfLink':'/apis/policy.mcm.ibm.com/v1alpha1/namespaces/mcm/policies/policy-pod',
      'annotations':{
        'policy.mcm.ibm.com/categories':'SystemAndCommunicationsProtections,SystemAndInformationIntegrity',
        'policy.mcm.ibm.com/controls':'MutationAdvisor,VA',
        'policy.mcm.ibm.com/standards':'NIST,HIPAA',
        'seed-generation':'1'
      },
      'resourceVersion':'5210306',
      '__typename':'Metadata'
    },
    'name':'policy-pod',
    'namespace':'mcm',
    'raw':{
      'apiVersion':'policy.mcm.ibm.com/v1alpha1',
      'kind':'Policy',
      'metadata':{
        'annotations':{
          'policy.mcm.ibm.com/categories':'SystemAndCommunicationsProtections,SystemAndInformationIntegrity',
          'policy.mcm.ibm.com/controls':'MutationAdvisor,VA',
          'policy.mcm.ibm.com/standards':'NIST,HIPAA',
          'seed-generation':'1'
        },
        'creationTimestamp':'2019-05-16T15:23:05Z',
        'finalizers':[
          'propagator.finalizer.mcm.ibm.com'
        ],
        'generation':12,
        'name':'policy-pod',
        'namespace':'mcm',
        'resourceVersion':'5210306',
        'selfLink':'/apis/policy.mcm.ibm.com/v1alpha1/namespaces/mcm/policies/policy-pod',
        'uid':'80b48466-77ee-11e9-a751-005056a0b88e'
      },
      'spec':{
        'complianceType':'musthave',
        'namespaces':{
          'exclude':[
            'kube*'
          ],
          'include':[
            'default'
          ]
        },
        'object-templates':[
          {
            'complianceType':'musthave',
            'objectDefinition':{
              'apiVersion':'v1',
              'kind':'Pod',
              'metadata':{
                'name':'nginx-pod'
              },
              'spec':{
                'containers':[
                  {
                    'image':'nginx:1.7.9',
                    'name':'nginx',
                    'ports':[
                      {
                        'containerPort':80
                      }
                    ]
                  }
                ]
              }
            },
            'status':{
              'Validity':{

              }
            }
          }
        ],
        'remediationAction':'inform'
      },
      'status':{
        'placementBindings':[
          'binding-pod'
        ],
        'placementPolicies':[
          'placement-pod'
        ],
        'status':{
          'cluster1':{
            'aggregatePoliciesStatus':{
              'policy-pod':{
                'compliant':'NonCompliant'
              }
            },
            'clustername':'cluster1',
            'compliant':'NonCompliant'
          },
          'clusterhub':{
            'aggregatePoliciesStatus':{
              'policy-pod':{
                'compliant':'NonCompliant'
              }
            },
            'clustername':'clusterhub',
            'compliant':'NonCompliant'
          }
        }
      }
    },
    'remediation':'inform',
    'policyCompliant':'2/2',
    'clusterCompliant':'2/2',
    'placementPolicies':[
      {
        'metadata':{
          'name':'placement-pod',
          'selfLink':'/apis/mcm.ibm.com/v1alpha1/namespaces/mcm/placementpolicies/placement-pod',
          '__typename':'Metadata'
        },
        '__typename':'PlacementPolicy'
      }
    ],
    'placementBindings':[
      {
        'metadata':{
          'name':'binding-pod',
          'selfLink':'/apis/mcm.ibm.com/v1alpha1/namespaces/mcm/placementbindings/binding-pod',
          '__typename':'Metadata'
        },
        '__typename':'PlacementBinding'
      }
    ],
    '__typename':'Compliance'
  },
]
