/** *****************************************************************************
 * Licensed Materials - Property of IBM
 * (c) Copyright IBM Corporation 2019. All Rights Reserved.
 *
 * Note to U.S. Government Users Restricted Rights:
 * Use, duplication or disclosure restricted by GSA ADP Schedule
 * Contract with IBM Corp.
 ****************************************************************************** */

export const policiesTestingDataSet1 = [
  {
    'metadata':{
      'name':'compliance-all',
      'namespace':'mcm',
      'selfLink':'/apis/compliance.mcm.ibm.com/v1alpha1/namespaces/mcm/compliances/compliance-all',
      'annotations':{
        'seed-generation':'1'
      },
      'resourceVersion':'1071070',
      '__typename':'Metadata'
    },
    'name':'compliance-all',
    'namespace':'mcm',
    'raw':{
      'apiVersion':'compliance.mcm.ibm.com/v1alpha1',
      'kind':'Compliance',
      'metadata':{
        'annotations':{
          'seed-generation':'1'
        },
        'creationTimestamp':'2019-05-21T14:02:49Z',
        'finalizers':[
          'propagator.finalizer.mcm.ibm.com'
        ],
        'generation':6,
        'name':'compliance-all',
        'namespace':'mcm',
        'resourceVersion':'1071070',
        'selfLink':'/apis/compliance.mcm.ibm.com/v1alpha1/namespaces/mcm/compliances/compliance-all',
        'uid':'1e04ec63-7bd1-11e9-820c-005056a061f1'
      },
      'spec':{
        'runtime-rules':[
          {
            'apiVersion':'policy.mcm.ibm.com/v1alpha1',
            'kind':'Policy',
            'metadata':{
              'creationTimestamp':null,
              'labels':{
                'cis-docker':'true'
              },
              'name':'policy-comp'
            },
            'spec':{
              'complianceType':'musthave',
              'namespaces':{
                'exclude':[
                  'kube*'
                ],
                'include':[
                  'default'
                ]
              },
              'object-templates':[
                {
                  'complianceType':'musthave',
                  'objectDefinition':{
                    'apiVersion':'rbac.authorization.k8s.io/v1',
                    'kind':'RoleBinding',
                    'metadata':{
                      'name':'operate-pods-rolebinding',
                      'namespace':'default'
                    },
                    'roleRef':{
                      'apiGroup':'rbac.authorization.k8s.io',
                      'kind':'Role',
                      'name':'operator'
                    },
                    'subjects':[
                      {
                        'apiGroup':'rbac.authorization.k8s.io',
                        'kind':'User',
                        'name':'admin'
                      }
                    ]
                  },
                  'status':{
                    'Validity':{

                    }
                  }
                },
                {
                  'complianceType':'musthave',
                  'objectDefinition':{
                    'apiVersion':'policy/v1beta1',
                    'kind':'PodSecurityPolicy',
                    'metadata':{
                      'annotations':{
                        'seccomp.security.alpha.kubernetes.io/allowedProfileNames':'*'
                      },
                      'name':'restricted-mcm'
                    },
                    'spec':{
                      'allowPrivilegeEscalation':false,
                      'allowedCapabilities':[
                        '*'
                      ],
                      'fsGroup':{
                        'rule':'RunAsAny'
                      },
                      'hostIPC':false,
                      'hostNetwork':true,
                      'hostPID':false,
                      'hostPorts':[
                        {
                          'max':65535,
                          'min':1000
                        }
                      ],
                      'privileged':false,
                      'runAsUser':{
                        'rule':'RunAsAny'
                      },
                      'seLinux':{
                        'rule':'RunAsAny'
                      },
                      'supplementalGroups':{
                        'rule':'RunAsAny'
                      },
                      'volumes':[
                        '*'
                      ]
                    }
                  },
                  'status':{
                    'Validity':{

                    }
                  }
                },
                {
                  'complianceType':'musthave',
                  'objectDefinition':{
                    'apiVersion':'networking.k8s.io/v1',
                    'kind':'NetworkPolicy',
                    'metadata':{
                      'name':'deny-from-other-namespaces',
                      'namespace':'default'
                    },
                    'spec':{
                      'ingress':[
                        {
                          'from':[
                            {
                              'podSelector':{

                              }
                            }
                          ]
                        }
                      ],
                      'podSelector':{
                        'matchLabels':null
                      }
                    }
                  },
                  'status':{
                    'Validity':{

                    }
                  }
                },
                {
                  'complianceType':'musthave',
                  'objectDefinition':{
                    'apiVersion':'v1',
                    'kind':'LimitRange',
                    'metadata':{
                      'name':'mem-limit-range'
                    },
                    'spec':{
                      'limits':[
                        {
                          'default':{
                            'memory':'512Mi'
                          },
                          'defaultRequest':{
                            'memory':'256Mi'
                          },
                          'type':'Container'
                        }
                      ]
                    }
                  },
                  'status':{
                    'Validity':{

                    }
                  }
                }
              ],
              'remediationAction':'inform',
              'role-templates':[
                {
                  'apiVersion':'roletemplate.mcm.ibm.com/v1alpha1',
                  'complianceType':'musthave',
                  'metadata':{
                    'creationTimestamp':null,
                    'name':'operator-role'
                  },
                  'rules':[
                    {
                      'complianceType':'mustnothave',
                      'policyRule':{
                        'apiGroups':[
                          'core'
                        ],
                        'resources':[
                          'secrets'
                        ],
                        'verbs':[
                          'get',
                          'list',
                          'watch',
                          'delete',
                          'create',
                          'update',
                          'patch'
                        ]
                      }
                    },
                    {
                      'complianceType':'musthave',
                      'policyRule':{
                        'apiGroups':[
                          'core'
                        ],
                        'resources':[
                          'pods'
                        ],
                        'verbs':[
                          'get',
                          'list',
                          'watch'
                        ]
                      }
                    }
                  ],
                  'selector':{
                    'matchLabels':{
                      'dev':'true'
                    }
                  },
                  'status':{
                    'Validity':{

                    }
                  }
                }
              ]
            },
            'status':{

            }
          }
        ]
      },
      'status':{
        'placementBindings':[
          'binding-comp'
        ],
        'placementPolicies':[
          'placement-comp'
        ],
        'status':{
          'cluster1':{
            'aggregatePoliciesStatus':{
              'policy-comp':{
                'compliant':'NonCompliant',
                'valid':true
              }
            },
            'clustername':'cluster1',
            'compliant':'NonCompliant'
          },
          'clusterhub':{
            'aggregatePoliciesStatus':{
              'policy-comp':{
                'compliant':'NonCompliant',
                'valid':true
              }
            },
            'clustername':'clusterhub',
            'compliant':'NonCompliant'
          }
        }
      }
    },
    'remediation':'',
    'policyCompliant':'2/2',
    'clusterCompliant':'2/2',
    'placementPolicies':[
      {
        'metadata':{
          'name':'placement-comp',
          'selfLink':'/apis/mcm.ibm.com/v1alpha1/namespaces/mcm/placementpolicies/placement-comp',
          '__typename':'Metadata'
        },
        '__typename':'PlacementPolicy'
      }
    ],
    'placementBindings':[
      {
        'metadata':{
          'name':'binding-comp',
          'selfLink':'/apis/mcm.ibm.com/v1alpha1/namespaces/mcm/placementbindings/binding-comp',
          '__typename':'Metadata'
        },
        '__typename':'PlacementBinding'
      }
    ],
    '__typename':'Compliance'
  },
  {
    'metadata':{
      'name':'policy-ma',
      'namespace':'mcm',
      'selfLink':'/apis/policy.mcm.ibm.com/v1alpha1/namespaces/mcm/policies/policy-ma',
      'annotations':{
        'policy.mcm.ibm.com/categories':'SystemAndInformationIntegrity',
        'policy.mcm.ibm.com/controls':'MutationAdvisor',
        'policy.mcm.ibm.com/standards':'NIST',
        'seed-generation':'1'
      },
      'resourceVersion':'1308515',
      '__typename':'Metadata'
    },
    'name':'policy-ma',
    'namespace':'mcm',
    'raw':{
      'apiVersion':'policy.mcm.ibm.com/v1alpha1',
      'kind':'Policy',
      'metadata':{
        'annotations':{
          'policy.mcm.ibm.com/categories':'SystemAndInformationIntegrity',
          'policy.mcm.ibm.com/controls':'MutationAdvisor',
          'policy.mcm.ibm.com/standards':'NIST',
          'seed-generation':'1'
        },
        'creationTimestamp':'2019-05-17T12:58:05Z',
        'finalizers':[
          'propagator.finalizer.mcm.ibm.com'
        ],
        'generation':22,
        'name':'policy-ma',
        'namespace':'mcm',
        'resourceVersion':'1308515',
        'selfLink':'/apis/policy.mcm.ibm.com/v1alpha1/namespaces/mcm/policies/policy-ma',
        'uid':'692d81a1-78a3-11e9-820c-005056a061f1'
      },
      'spec':{
        'namespaces':{

        },
        'policy-templates':[
          {
            'objectDefinition':{
              'apiVersion':'policies.ibm.com/v1alpha1',
              'kind':'MutationPolicy',
              'metadata':{
                'label':{
                  'category':'System-Integrity'
                },
                'name':'mutation-policy-example'
              },
              'spec':{
                'conditions':{
                  'ownership':[
                    'ReplicaSet',
                    'Deployment',
                    'DeamonSet',
                    'ReplicationController'
                  ]
                },
                'namespaceSelector':{
                  'exclude':[
                    'kube-system'
                  ],
                  'include':[
                    'default',
                    'kube-*'
                  ]
                },
                'remediationAction':'enforce'
              }
            },
            'status':{
              'Validity':{

              }
            }
          }
        ],
        'remediationAction':'enforce'
      },
      'status':{
        'placementBindings':[
          'binding-ma'
        ],
        'placementPolicies':[
          'placement-ma'
        ],
        'status':{
          'cluster1':{
            'aggregatePoliciesStatus':{
              'policy-ma':{
                'compliant':'NonCompliant'
              }
            },
            'clustername':'cluster1',
            'compliant':'NonCompliant'
          },
          'clusterhub':{
            'aggregatePoliciesStatus':{
              'policy-ma':{
                'compliant':'Compliant'
              }
            },
            'clustername':'clusterhub',
            'compliant':'Compliant'
          }
        }
      }
    },
    'remediation':'enforce',
    'policyCompliant':'1/2',
    'clusterCompliant':'1/2',
    'placementPolicies':[
      {
        'metadata':{
          'name':'placement-ma',
          'selfLink':'/apis/mcm.ibm.com/v1alpha1/namespaces/mcm/placementpolicies/placement-ma',
          '__typename':'Metadata'
        },
        '__typename':'PlacementPolicy'
      }
    ],
    'placementBindings':[
      {
        'metadata':{
          'name':'binding-ma',
          'selfLink':'/apis/mcm.ibm.com/v1alpha1/namespaces/mcm/placementbindings/binding-ma',
          '__typename':'Metadata'
        },
        '__typename':'PlacementBinding'
      }
    ],
    '__typename':'Compliance'
  },
  {
    'metadata':{
      'name':'policy-pod',
      'namespace':'mcm',
      'selfLink':'/apis/policy.mcm.ibm.com/v1alpha1/namespaces/mcm/policies/policy-pod',
      'annotations':{
        'policy.mcm.ibm.com/categories':'SystemAndCommunicationsProtections,SystemAndInformationIntegrity',
        'policy.mcm.ibm.com/controls':'MutationAdvisor,VA',
        'policy.mcm.ibm.com/standards':'NIST,HIPAA',
        'seed-generation':'1'
      },
      'resourceVersion':'131792',
      '__typename':'Metadata'
    },
    'name':'policy-pod',
    'namespace':'mcm',
    'raw':{
      'apiVersion':'policy.mcm.ibm.com/v1alpha1',
      'kind':'Policy',
      'metadata':{
        'annotations':{
          'policy.mcm.ibm.com/categories':'SystemAndCommunicationsProtections,SystemAndInformationIntegrity',
          'policy.mcm.ibm.com/controls':'MutationAdvisor,VA',
          'policy.mcm.ibm.com/standards':'NIST,HIPAA',
          'seed-generation':'1'
        },
        'creationTimestamp':'2019-05-17T12:57:48Z',
        'finalizers':[
          'propagator.finalizer.mcm.ibm.com'
        ],
        'generation':7,
        'name':'policy-pod',
        'namespace':'mcm',
        'resourceVersion':'131792',
        'selfLink':'/apis/policy.mcm.ibm.com/v1alpha1/namespaces/mcm/policies/policy-pod',
        'uid':'5f3aea80-78a3-11e9-820c-005056a061f1'
      },
      'spec':{
        'complianceType':'musthave',
        'namespaces':{
          'exclude':[
            'kube*'
          ],
          'include':[
            'default'
          ]
        },
        'object-templates':[
          {
            'complianceType':'musthave',
            'objectDefinition':{
              'apiVersion':'v1',
              'kind':'Pod',
              'metadata':{
                'name':'nginx-pod'
              },
              'spec':{
                'containers':[
                  {
                    'image':'nginx:1.7.9',
                    'name':'nginx',
                    'ports':[
                      {
                        'containerPort':80
                      }
                    ]
                  }
                ]
              }
            },
            'status':{
              'Validity':{

              }
            }
          }
        ],
        'remediationAction':'inform'
      },
      'status':{
        'placementBindings':[
          'binding-pod'
        ],
        'placementPolicies':[
          'placement-pod'
        ],
        'status':{
          'cluster1':{
            'aggregatePoliciesStatus':{
              'policy-pod':{
                'compliant':'NonCompliant'
              }
            },
            'clustername':'cluster1',
            'compliant':'NonCompliant'
          },
          'clusterhub':{
            'aggregatePoliciesStatus':{
              'policy-pod':{
                'compliant':'NonCompliant'
              }
            },
            'clustername':'clusterhub',
            'compliant':'NonCompliant'
          }
        }
      }
    },
    'remediation':'inform',
    'policyCompliant':'2/2',
    'clusterCompliant':'2/2',
    'placementPolicies':[
      {
        'metadata':{
          'name':'placement-pod',
          'selfLink':'/apis/mcm.ibm.com/v1alpha1/namespaces/mcm/placementpolicies/placement-pod',
          '__typename':'Metadata'
        },
        '__typename':'PlacementPolicy'
      }
    ],
    'placementBindings':[
      {
        'metadata':{
          'name':'binding-pod',
          'selfLink':'/apis/mcm.ibm.com/v1alpha1/namespaces/mcm/placementbindings/binding-pod',
          '__typename':'Metadata'
        },
        '__typename':'PlacementBinding'
      }
    ],
    '__typename':'Compliance'
  },
]

export const policiesTestingDataSet2 = [
  {
    'metadata':{
      'name':'1558374675051-policy-pod',
      'namespace':'mcm',
      'selfLink':'/apis/policy.mcm.ibm.com/v1alpha1/namespaces/mcm/policies/1558374675051-policy-pod',
      'annotations':{
        'policy.mcm.ibm.com/categories':'SystemAndCommunicationsProtections,SystemAndInformationIntegrity',
        'policy.mcm.ibm.com/controls':'MutationAdvisor,VA',
        'policy.mcm.ibm.com/standards':'NIST',
        'seed-generation':'2'
      },
      'resourceVersion':'6281988',
      '__typename':'Metadata'
    },
    'name':'1558374675051-policy-pod',
    'namespace':'mcm',
    'raw':{
      'apiVersion':'policy.mcm.ibm.com/v1alpha1',
      'kind':'Policy',
      'metadata':{
        'annotations':{
          'policy.mcm.ibm.com/categories':'SystemAndCommunicationsProtections,SystemAndInformationIntegrity',
          'policy.mcm.ibm.com/controls':'MutationAdvisor,VA',
          'policy.mcm.ibm.com/standards':'NIST',
          'seed-generation':'2'
        },
        'creationTimestamp':'2019-05-20T17:51:38Z',
        'finalizers':[
          'propagator.finalizer.mcm.ibm.com'
        ],
        'generation':6,
        'name':'1558374675051-policy-pod',
        'namespace':'mcm',
        'resourceVersion':'6281988',
        'selfLink':'/apis/policy.mcm.ibm.com/v1alpha1/namespaces/mcm/policies/1558374675051-policy-pod',
        'uid':'eacbfd03-7b27-11e9-a751-005056a0b88e'
      },
      'spec':{
        'complianceType':'musthave',
        'namespaces':{
          'exclude':[
            'kube*'
          ],
          'include':[
            'default'
          ]
        },
        'object-templates':[
          {
            'complianceType':'musthave',
            'objectDefinition':{
              'apiVersion':'v1',
              'kind':'Pod',
              'metadata':{
                'name':'nginx1'
              },
              'spec':{
                'containers':[
                  {
                    'image':'nginx:1.7.9',
                    'name':'nginx',
                    'ports':[
                      {
                        'containerPort':80
                      }
                    ]
                  }
                ]
              }
            },
            'status':{
              'Validity':{

              }
            }
          }
        ],
        'remediationAction':'inform'
      },
      'status':{
        'placementBindings':[
          '1558374675051-placement-binding-test'
        ],
        'placementPolicies':[
          '1558374675051-placement-policy-test'
        ],
        'status':{
          'cluster1':{
            'aggregatePoliciesStatus':{
              '1558374675051-policy-pod':{
                'compliant':'NonCompliant'
              }
            },
            'clustername':'cluster1',
            'compliant':'NonCompliant'
          },
          'clusterhub':{
            'aggregatePoliciesStatus':{
              '1558374675051-policy-pod':{
                'compliant':'NonCompliant'
              }
            },
            'clustername':'clusterhub',
            'compliant':'NonCompliant'
          }
        }
      }
    },
    'remediation':'inform',
    'policyCompliant':'2/2',
    'clusterCompliant':'2/2',
    'placementPolicies':[
      {
        'metadata':{
          'name':'1558374675051-placement-policy-test',
          'selfLink':'/apis/mcm.ibm.com/v1alpha1/namespaces/mcm/placementpolicies/1558374675051-placement-policy-test',
          '__typename':'Metadata'
        },
        '__typename':'PlacementPolicy'
      }
    ],
    'placementBindings':[
      {
        'metadata':{
          'name':'1558374675051-placement-binding-test',
          'selfLink':'/apis/mcm.ibm.com/v1alpha1/namespaces/mcm/placementbindings/1558374675051-placement-binding-test',
          '__typename':'Metadata'
        },
        '__typename':'PlacementBinding'
      }
    ],
    '__typename':'Compliance'
  },
  {
    'metadata':{
      'name':'1558382034240-policy-pod',
      'namespace':'mcm',
      'selfLink':'/apis/policy.mcm.ibm.com/v1alpha1/namespaces/mcm/policies/1558382034240-policy-pod',
      'annotations':{
        'policy.mcm.ibm.com/categories':'SystemAndCommunicationsProtections,SystemAndInformationIntegrity',
        'policy.mcm.ibm.com/controls':'MutationAdvisor,VA',
        'policy.mcm.ibm.com/standards':'NIST',
        'seed-generation':'2'
      },
      'resourceVersion':'6975805',
      '__typename':'Metadata'
    },
    'name':'1558382034240-policy-pod',
    'namespace':'mcm',
    'raw':{
      'apiVersion':'policy.mcm.ibm.com/v1alpha1',
      'kind':'Policy',
      'metadata':{
        'annotations':{
          'policy.mcm.ibm.com/categories':'SystemAndCommunicationsProtections,SystemAndInformationIntegrity',
          'policy.mcm.ibm.com/controls':'MutationAdvisor,VA',
          'policy.mcm.ibm.com/standards':'NIST',
          'seed-generation':'2'
        },
        'creationTimestamp':'2019-05-20T19:54:18Z',
        'finalizers':[
          'propagator.finalizer.mcm.ibm.com'
        ],
        'generation':11,
        'name':'1558382034240-policy-pod',
        'namespace':'mcm',
        'resourceVersion':'6975805',
        'selfLink':'/apis/policy.mcm.ibm.com/v1alpha1/namespaces/mcm/policies/1558382034240-policy-pod',
        'uid':'0d98fa74-7b39-11e9-a751-005056a0b88e'
      },
      'spec':{
        'complianceType':'musthave',
        'namespaces':{
          'exclude':[
            'kube*'
          ],
          'include':[
            'default'
          ]
        },
        'object-templates':[
          {
            'complianceType':'musthave',
            'objectDefinition':{
              'apiVersion':'v1',
              'kind':'Pod',
              'metadata':{
                'name':'nginx1'
              },
              'spec':{
                'containers':[
                  {
                    'image':'nginx:1.7.9',
                    'name':'nginx',
                    'ports':[
                      {
                        'containerPort':80
                      }
                    ]
                  }
                ]
              }
            },
            'status':{
              'Validity':{

              }
            }
          }
        ],
        'remediationAction':'inform'
      },
      'status':{
        'placementBindings':[
          '1558382034240-placement-binding-test'
        ],
        'placementPolicies':[
          '1558382034240-placement-policy-test'
        ],
        'status':{
          'cluster1':{
            'aggregatePoliciesStatus':{
              '1558382034240-policy-pod':{
                'compliant':'NonCompliant'
              }
            },
            'clustername':'cluster1',
            'compliant':'NonCompliant'
          },
          'clusterhub':{
            'aggregatePoliciesStatus':{
              '1558382034240-policy-pod':{
                'compliant':'NonCompliant'
              }
            },
            'clustername':'clusterhub',
            'compliant':'NonCompliant'
          }
        }
      }
    },
    'remediation':'inform',
    'policyCompliant':'2/2',
    'clusterCompliant':'2/2',
    'placementPolicies':[
      {
        'metadata':{
          'name':'1558382034240-placement-policy-test',
          'selfLink':'/apis/mcm.ibm.com/v1alpha1/namespaces/mcm/placementpolicies/1558382034240-placement-policy-test',
          '__typename':'Metadata'
        },
        '__typename':'PlacementPolicy'
      }
    ],
    'placementBindings':[
      {
        'metadata':{
          'name':'1558382034240-placement-binding-test',
          'selfLink':'/apis/mcm.ibm.com/v1alpha1/namespaces/mcm/placementbindings/1558382034240-placement-binding-test',
          '__typename':'Metadata'
        },
        '__typename':'PlacementBinding'
      }
    ],
    '__typename':'Compliance'
  },
  {
    'metadata':{
      'name':'policy-ma',
      'namespace':'mcm',
      'selfLink':'/apis/policy.mcm.ibm.com/v1alpha1/namespaces/mcm/policies/policy-ma',
      'annotations':{
        'policy.mcm.ibm.com/categories':'SystemAndInformationIntegrity',
        'policy.mcm.ibm.com/controls':'MutationAdvisor',
        'policy.mcm.ibm.com/standards':'NIST',
        'seed-generation':'1'
      },
      'resourceVersion':'6975864',
      '__typename':'Metadata'
    },
    'name':'policy-ma',
    'namespace':'mcm',
    'raw':{
      'apiVersion':'policy.mcm.ibm.com/v1alpha1',
      'kind':'Policy',
      'metadata':{
        'annotations':{
          'policy.mcm.ibm.com/categories':'SystemAndInformationIntegrity',
          'policy.mcm.ibm.com/controls':'MutationAdvisor',
          'policy.mcm.ibm.com/standards':'NIST',
          'seed-generation':'1'
        },
        'creationTimestamp':'2019-05-16T15:21:53Z',
        'finalizers':[
          'propagator.finalizer.mcm.ibm.com'
        ],
        'generation':48,
        'name':'policy-ma',
        'namespace':'mcm',
        'resourceVersion':'6975864',
        'selfLink':'/apis/policy.mcm.ibm.com/v1alpha1/namespaces/mcm/policies/policy-ma',
        'uid':'55ca144d-77ee-11e9-a751-005056a0b88e'
      },
      'spec':{
        'namespaces':{

        },
        'policy-templates':[
          {
            'objectDefinition':{
              'apiVersion':'policies.ibm.com/v1alpha1',
              'kind':'MutationPolicy',
              'metadata':{
                'label':{
                  'category':'System-Integrity'
                },
                'name':'mutation-policy-example'
              },
              'spec':{
                'conditions':{
                  'ownership':[
                    'ReplicaSet',
                    'Deployment',
                    'DeamonSet',
                    'ReplicationController'
                  ]
                },
                'namespaceSelector':{
                  'exclude':[
                    'kube-system'
                  ],
                  'include':[
                    'default',
                    'kube-*'
                  ]
                },
                'remediationAction':'enforce'
              }
            },
            'status':{
              'Validity':{

              }
            }
          }
        ],
        'remediationAction':'enforce'
      },
      'status':{
        'placementBindings':[
          'binding-ma'
        ],
        'placementPolicies':[
          'placement-ma'
        ],
        'status':{
          'cluster1':{
            'aggregatePoliciesStatus':{
              'policy-ma':{
                'compliant':'Compliant'
              }
            },
            'clustername':'cluster1',
            'compliant':'Compliant'
          },
          'clusterhub':{
            'aggregatePoliciesStatus':{
              'policy-ma':{
                'compliant':'Compliant'
              }
            },
            'clustername':'clusterhub',
            'compliant':'Compliant'
          }
        }
      }
    },
    'remediation':'enforce',
    'policyCompliant':'0/2',
    'clusterCompliant':'0/2',
    'placementPolicies':[
      {
        'metadata':{
          'name':'placement-ma',
          'selfLink':'/apis/mcm.ibm.com/v1alpha1/namespaces/mcm/placementpolicies/placement-ma',
          '__typename':'Metadata'
        },
        '__typename':'PlacementPolicy'
      }
    ],
    'placementBindings':[
      {
        'metadata':{
          'name':'binding-ma',
          'selfLink':'/apis/mcm.ibm.com/v1alpha1/namespaces/mcm/placementbindings/binding-ma',
          '__typename':'Metadata'
        },
        '__typename':'PlacementBinding'
      }
    ],
    '__typename':'Compliance'
  },
  {
    'metadata':{
      'name':'policy-pod',
      'namespace':'mcm',
      'selfLink':'/apis/policy.mcm.ibm.com/v1alpha1/namespaces/mcm/policies/policy-pod',
      'annotations':{
        'policy.mcm.ibm.com/categories':'SystemAndCommunicationsProtections,SystemAndInformationIntegrity',
        'policy.mcm.ibm.com/controls':'MutationAdvisor,VA',
        'policy.mcm.ibm.com/standards':'NIST,HIPAA',
        'seed-generation':'1'
      },
      'resourceVersion':'5210306',
      '__typename':'Metadata'
    },
    'name':'policy-pod',
    'namespace':'mcm',
    'raw':{
      'apiVersion':'policy.mcm.ibm.com/v1alpha1',
      'kind':'Policy',
      'metadata':{
        'annotations':{
          'policy.mcm.ibm.com/categories':'SystemAndCommunicationsProtections,SystemAndInformationIntegrity',
          'policy.mcm.ibm.com/controls':'MutationAdvisor,VA',
          'policy.mcm.ibm.com/standards':'NIST,HIPAA',
          'seed-generation':'1'
        },
        'creationTimestamp':'2019-05-16T15:23:05Z',
        'finalizers':[
          'propagator.finalizer.mcm.ibm.com'
        ],
        'generation':12,
        'name':'policy-pod',
        'namespace':'mcm',
        'resourceVersion':'5210306',
        'selfLink':'/apis/policy.mcm.ibm.com/v1alpha1/namespaces/mcm/policies/policy-pod',
        'uid':'80b48466-77ee-11e9-a751-005056a0b88e'
      },
      'spec':{
        'complianceType':'musthave',
        'namespaces':{
          'exclude':[
            'kube*'
          ],
          'include':[
            'default'
          ]
        },
        'object-templates':[
          {
            'complianceType':'musthave',
            'objectDefinition':{
              'apiVersion':'v1',
              'kind':'Pod',
              'metadata':{
                'name':'nginx-pod'
              },
              'spec':{
                'containers':[
                  {
                    'image':'nginx:1.7.9',
                    'name':'nginx',
                    'ports':[
                      {
                        'containerPort':80
                      }
                    ]
                  }
                ]
              }
            },
            'status':{
              'Validity':{

              }
            }
          }
        ],
        'remediationAction':'inform'
      },
      'status':{
        'placementBindings':[
          'binding-pod'
        ],
        'placementPolicies':[
          'placement-pod'
        ],
        'status':{
          'cluster1':{
            'aggregatePoliciesStatus':{
              'policy-pod':{
                'compliant':'NonCompliant'
              }
            },
            'clustername':'cluster1',
            'compliant':'NonCompliant'
          },
          'clusterhub':{
            'aggregatePoliciesStatus':{
              'policy-pod':{
                'compliant':'NonCompliant'
              }
            },
            'clustername':'clusterhub',
            'compliant':'NonCompliant'
          }
        }
      }
    },
    'remediation':'inform',
    'policyCompliant':'2/2',
    'clusterCompliant':'2/2',
    'placementPolicies':[
      {
        'metadata':{
          'name':'placement-pod',
          'selfLink':'/apis/mcm.ibm.com/v1alpha1/namespaces/mcm/placementpolicies/placement-pod',
          '__typename':'Metadata'
        },
        '__typename':'PlacementPolicy'
      }
    ],
    'placementBindings':[
      {
        'metadata':{
          'name':'binding-pod',
          'selfLink':'/apis/mcm.ibm.com/v1alpha1/namespaces/mcm/placementbindings/binding-pod',
          '__typename':'Metadata'
        },
        '__typename':'PlacementBinding'
      }
    ],
    '__typename':'Compliance'
  },
]

export const policieSubResourceListTestingResourceData = {
  'headerRows':[
    '',
    'table.header.cluster.name',
    'table.header.rule.violation'
  ],
  'subHeaders':[
    'table.header.name',
    'table.header.message',
    'table.header.reason'
  ],
  'rows':[
    {
      'cells':[
        {
          'resourceKey':'metadata.name'
        },
        {
          'resourceKey':'violated'
        },
        {
          'resourceKey':'spec.consoleURL'
        }
      ]
    }
  ]
}

export const policieSubResourceListTestingItemData = [
  {
    'name':'cluster1',
    'metadata':{
      'labels':{
        'cloud':'IBM',
        'datacenter':'toronto',
        'environment':'Dev',
        'name':'cluster1',
        'owner':'marketing',
        'region':'US',
        'vendor':'ICP'
      },
      'name':'cluster1',
      'namespace':'cluster1',
      'annotations':{
        'mcm.ibm.com/deployer-prefix':'md',
        'mcm.ibm.com/secretRef':'cluster1-federation-secret',
        'mcm.ibm.com/user-group':'aGNtOmNsdXN0ZXJzLHN5c3RlbTphdXRoZW50aWNhdGVk',
        'mcm.ibm.com/user-identity':'aGNtOmNsdXN0ZXJzOmNsdXN0ZXIxOmNsdXN0ZXIx'
      },
      'uid':'3037958c-8168-11e9-8492-1640a90e9b43',
      'selfLink':'/apis/mcm.ibm.com/v1alpha1/namespaces/cluster1/clusterstatuses/cluster1',
      '__typename':'Metadata'
    },
    'kind':'Cluster',
    'apiVersion':'clusterregistry.k8s.io/v1alpha1',
    'spec':{
      'masterAddresses':[
        {
          'ip':'9.42.78.148'
        }
      ],
      'consoleURL':'https://9.42.78.148:8443',
      'capacity':{
        'cpu':'32',
        'memory':'64186Mi',
        'nodes':'4',
        'storage':'90Gi'
      },
      'usage':{
        'cpu':'11808m',
        'memory':'33015Mi',
        'pods':'141',
        'storage':'90Gi'
      },
      'klusterletEndpoint':{
        'ip':'9.42.78.148',
        'hostname':'cluster1.klusterlet.mcm'
      },
      'klusterletPort':{
        'name':'https',
        'port':443,
        'protocol':'TCP'
      },
      'klusterletVersion':'3.2.0',
      'version':'v1.13.5+icp-ee',
      'klusterletCA':'LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURDakNDQWZLZ0F3SUJBZ0lRZEprK0ZqdkJvMGFqMW9oQ2ppSmZZVEFOQmdrcWhraUc5dzBCQVFzRkFEQWoKTVF3d0NnWURWUVFLRXdOSlFrMHhFekFSQmdOVkJBTVRDbXRzZFhOMFpYSnNaWFF3SGhjTk1Ua3dOVEk0TVRVeQpNVEUxV2hjTk1Ua3dPREkyTVRVeU1URTFXakFqTVF3d0NnWURWUVFLRXdOSlFrMHhFekFSQmdOVkJBTVRDbXRzCmRYTjBaWEpzWlhRd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUJEd0F3Z2dFS0FvSUJBUUNwZXZxdFI1RmwKT0dhVnQwVys1WGRKdW1FWllUbFNKeGJhM1VJSmtiOHo2MVNsV0Qzd2diQ2ZzdWdRUFYvajdDS3daUGJ3L2YyQQp6OXJPWjlRbldIbXkzamQ4a2NCUVpTYnhCR29NRVhVSGtod3BlZ25hUmsrdGEvUnlRTk1QWHFwWFVMV2VHazdjCjdablBqL3JTak5wT1hkM0JxeW9rNG9ranVVM3BQcnROL1NFMWt4OHlzWG1lNjk1Rytxd2xlcm9PSlVYOE1SSVcKbEFBVWhYTDJDcWU1UjNyR3ozMStCSVNxWVpMbzFoNEtUamNpVVQ5M21BVXJJN2JWQ0dZWDdQdUNjQU9nQnR4WQpjR3k1eGtMQXYyVDVTOEVFZmNueEJQb1FJRm5jeHVncHkwT1BDaXBuVHR4QnpldE1Ld0liUFdySml5WVU5THFICmhsK1NuSEVOcTRpbEFnTUJBQUdqT2pBNE1BNEdBMVVkRHdFQi93UUVBd0lDcERBUEJnTlZIUk1CQWY4RUJUQUQKQVFIL01CVUdBMVVkRVFRT01BeUNDbXRzZFhOMFpYSnNaWFF3RFFZSktvWklodmNOQVFFTEJRQURnZ0VCQUtINApxcm1TM05QRGZkQzFLb2pvVHBHQlovNnZRTkh1cno0TFNJV0E2RE9wNk94Tis4VDlxL0I3UW5iOVBpdCtsUXJGCm9QbnQ2U05WVU5aRGRSSTlLU2Vlei9lcTV2bnBIbWtJNm82VTRVcytnNlp3YVhndXlhUzd3RUwxWkltQVlLMm4KSnVjUUJDZFRCT2hOZjAvZ3h0dmxRTWdjcHFoam0vMnlLOEt1b2VTT0dldCtobGhiTnFiUDJ6MTViNW0yWEI0WQplYVZzdkhrYVYxSWhOdXEvRTdKU0FZMldCaWo5d0ZmZ2t5cURqWWUxbWFoMG5GS2lpT3RXNERqdjhFSWQ4QXk3CkFYMXl4ZmNOSVVTbWErbXowcWRLVGorQVVjSUhmdlRMMjZ4SDd4cVhCdGZKc1NwbVMyelVTdjN3bnpRc1FxKzQKaHhYMGtTK0E2cmZNWkFkS3JIMD0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=',
      'monitoringEndpoint':{
        'ip':''
      },
      'monitoringPort':{
        'port':0
      },
      'monitoringSecretRef':{

      }
    },
    'status':{
      'conditions':[
        {
          'type':'OK',
          'status':'',
          'lastHeartbeatTime':'2019-06-04T21:17:45Z',
          'lastTransitionTime':null
        }
      ]
    },
    'total':'1',
    'violated':'1',
    'policy':{
      'apiVersion':'policy.mcm.ibm.com/v1alpha1',
      'kind':'Policy',
      'metadata':{
        'annotations':{
          'ownerUID':'8131e790-817f-11e9-983e-005056a061f1',
          'seed-generation':'185851'
        },
        'creationTimestamp':'2019-05-28T19:33:44Z',
        'finalizers':[
          'sync.finalizer.mcm.ibm.com',
          'policy.finalizer.mcm.ibm.com'
        ],
        'generation':185851,
        'name':'policy-pod',
        'namespace':'cluster1',
        'resourceVersion':'1682676',
        'selfLink':'/apis/policy.mcm.ibm.com/v1alpha1/namespaces/cluster1/policies/policy-pod',
        'uid':'813518d5-817f-11e9-af27-005056a0e992'
      },
      'spec':{
        'complianceType':'musthave',
        'namespaces':{
          'exclude':[
            'kube*'
          ],
          'include':[
            'default'
          ]
        },
        'object-templates':[
          {
            'complianceType':'musthave',
            'objectDefinition':{
              'apiVersion':'v1',
              'kind':'Pod',
              'metadata':{
                'name':'nginx-pod'
              },
              'spec':{
                'containers':[
                  {
                    'image':'nginx:1.7.9',
                    'name':'nginx',
                    'ports':[
                      {
                        'containerPort':80
                      }
                    ]
                  }
                ]
              }
            },
            'status':{
              'Compliant':'NonCompliant',
              'Validity':{

              },
              'conditions':[
                {
                  'lastTransitionTime':'2019-06-04T21:18:14Z',
                  'message':'pods `nginx-pod` is missing, and should be created',
                  'reason':'K8s missing a must have object',
                  'status':'True',
                  'type':'violation'
                }
              ]
            }
          }
        ],
        'remediationAction':'inform'
      },
      'status':{
        'compliant':'NonCompliant'
      }
    },
    '__typename':'ClusterInfo',
    'subItems':[
      {
        'id':'nginx-pod',
        'cells':[
          'nginx-pod',
          'pods `nginx-pod` is missing, and should be created',
          'K8s missing a must have object'
        ]
      }
    ]
  },
  {
    'name':'clusterhub',
    'metadata':{
      'labels':{
        'cloud':'IBM',
        'datacenter':'toronto',
        'environment':'Dev',
        'name':'clusterhub',
        'owner':'marketing',
        'region':'US',
        'vendor':'ICP'
      },
      'name':'clusterhub',
      'namespace':'clusterhub',
      'annotations':{
        'mcm.ibm.com/deployer-prefix':'md',
        'mcm.ibm.com/secretRef':'clusterhub-federation-secret',
        'mcm.ibm.com/user-group':'aGNtOmNsdXN0ZXJzLHN5c3RlbTphdXRoZW50aWNhdGVk',
        'mcm.ibm.com/user-identity':'aGNtOmNsdXN0ZXJzOmNsdXN0ZXJodWI6Y2x1c3Rlcmh1Yg=='
      },
      'uid':'54065f57-815d-11e9-8492-1640a90e9b43',
      'selfLink':'/apis/mcm.ibm.com/v1alpha1/namespaces/clusterhub/clusterstatuses/clusterhub',
      '__typename':'Metadata'
    },
    'kind':'Cluster',
    'apiVersion':'clusterregistry.k8s.io/v1alpha1',
    'spec':{
      'masterAddresses':[
        {
          'ip':'9.42.81.137'
        }
      ],
      'consoleURL':'https://9.42.81.137:8443',
      'capacity':{
        'cpu':'32',
        'memory':'64186Mi',
        'nodes':'4',
        'storage':'90Gi'
      },
      'usage':{
        'cpu':'11833m',
        'memory':'32951Mi',
        'pods':'153',
        'storage':'90Gi'
      },
      'klusterletEndpoint':{
        'ip':'',
        'hostname':'mcmk-ibm-klusterlet-klusterlet.kube-system.svc'
      },
      'klusterletPort':{
        'name':'https',
        'port':443,
        'protocol':'TCP'
      },
      'klusterletVersion':'3.2.0-28+af74e41f54a768',
      'version':'v1.13.5+icp-ee',
      'klusterletCA':'LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURDakNDQWZLZ0F3SUJBZ0lRZEprK0ZqdkJvMGFqMW9oQ2ppSmZZVEFOQmdrcWhraUc5dzBCQVFzRkFEQWoKTVF3d0NnWURWUVFLRXdOSlFrMHhFekFSQmdOVkJBTVRDbXRzZFhOMFpYSnNaWFF3SGhjTk1Ua3dOVEk0TVRVeQpNVEUxV2hjTk1Ua3dPREkyTVRVeU1URTFXakFqTVF3d0NnWURWUVFLRXdOSlFrMHhFekFSQmdOVkJBTVRDbXRzCmRYTjBaWEpzWlhRd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUJEd0F3Z2dFS0FvSUJBUUNwZXZxdFI1RmwKT0dhVnQwVys1WGRKdW1FWllUbFNKeGJhM1VJSmtiOHo2MVNsV0Qzd2diQ2ZzdWdRUFYvajdDS3daUGJ3L2YyQQp6OXJPWjlRbldIbXkzamQ4a2NCUVpTYnhCR29NRVhVSGtod3BlZ25hUmsrdGEvUnlRTk1QWHFwWFVMV2VHazdjCjdablBqL3JTak5wT1hkM0JxeW9rNG9ranVVM3BQcnROL1NFMWt4OHlzWG1lNjk1Rytxd2xlcm9PSlVYOE1SSVcKbEFBVWhYTDJDcWU1UjNyR3ozMStCSVNxWVpMbzFoNEtUamNpVVQ5M21BVXJJN2JWQ0dZWDdQdUNjQU9nQnR4WQpjR3k1eGtMQXYyVDVTOEVFZmNueEJQb1FJRm5jeHVncHkwT1BDaXBuVHR4QnpldE1Ld0liUFdySml5WVU5THFICmhsK1NuSEVOcTRpbEFnTUJBQUdqT2pBNE1BNEdBMVVkRHdFQi93UUVBd0lDcERBUEJnTlZIUk1CQWY4RUJUQUQKQVFIL01CVUdBMVVkRVFRT01BeUNDbXRzZFhOMFpYSnNaWFF3RFFZSktvWklodmNOQVFFTEJRQURnZ0VCQUtINApxcm1TM05QRGZkQzFLb2pvVHBHQlovNnZRTkh1cno0TFNJV0E2RE9wNk94Tis4VDlxL0I3UW5iOVBpdCtsUXJGCm9QbnQ2U05WVU5aRGRSSTlLU2Vlei9lcTV2bnBIbWtJNm82VTRVcytnNlp3YVhndXlhUzd3RUwxWkltQVlLMm4KSnVjUUJDZFRCT2hOZjAvZ3h0dmxRTWdjcHFoam0vMnlLOEt1b2VTT0dldCtobGhiTnFiUDJ6MTViNW0yWEI0WQplYVZzdkhrYVYxSWhOdXEvRTdKU0FZMldCaWo5d0ZmZ2t5cURqWWUxbWFoMG5GS2lpT3RXNERqdjhFSWQ4QXk3CkFYMXl4ZmNOSVVTbWErbXowcWRLVGorQVVjSUhmdlRMMjZ4SDd4cVhCdGZKc1NwbVMyelVTdjN3bnpRc1FxKzQKaHhYMGtTK0E2cmZNWkFkS3JIMD0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=',
      'monitoringEndpoint':{
        'ip':''
      },
      'monitoringPort':{
        'port':0
      },
      'monitoringSecretRef':{

      }
    },
    'status':{
      'conditions':[
        {
          'type':'OK',
          'status':'',
          'lastHeartbeatTime':'2019-06-04T21:18:11Z',
          'lastTransitionTime':null
        }
      ]
    },
    'total':'3',
    'violated':'3',
    'policy':{
      'apiVersion':'policy.mcm.ibm.com/v1alpha1',
      'kind':'Policy',
      'metadata':{
        'annotations':{
          'policy.mcm.ibm.com/categories':'SystemAndCommunicationsProtections,SystemAndInformationIntegrity',
          'policy.mcm.ibm.com/controls':'MutationAdvisor,VA',
          'policy.mcm.ibm.com/standards':'NIST,HIPAA',
          'seed-generation':'1'
        },
        'creationTimestamp':'2019-05-28T19:33:43Z',
        'finalizers':[
          'propagator.finalizer.mcm.ibm.com'
        ],
        'generation':7,
        'name':'policy-pod',
        'namespace':'mcm',
        'resourceVersion':'41023',
        'selfLink':'/apis/policy.mcm.ibm.com/v1alpha1/namespaces/mcm/policies/policy-pod',
        'uid':'80fd0634-817f-11e9-983e-005056a061f1'
      },
      'spec':{
        'complianceType':'musthave',
        'namespaces':{
          'exclude':[
            'kube*'
          ],
          'include':[
            'default'
          ]
        },
        'object-templates':[
          {
            'complianceType':'musthave',
            'objectDefinition':{
              'apiVersion':'v1',
              'kind':'Pod',
              'metadata':{
                'name':'nginx-pod'
              },
              'spec':{
                'containers':[
                  {
                    'image':'nginx:1.7.9',
                    'name':'nginx',
                    'ports':[
                      {
                        'containerPort':80
                      }
                    ]
                  }
                ]
              }
            },
            'status':{
              'Validity':{

              }
            }
          }
        ],
        'remediationAction':'inform'
      },
      'status':{
        'placementBindings':[
          'binding-pod'
        ],
        'placementPolicies':[
          'placement-pod'
        ],
        'status':{
          'cluster1':{
            'aggregatePoliciesStatus':{
              'policy-pod':{
                'compliant':'NonCompliant'
              }
            },
            'clustername':'cluster1',
            'compliant':'NonCompliant'
          },
          'clusterhub':{
            'aggregatePoliciesStatus':{
              'policy-pod':{
                'compliant':'NonCompliant'
              }
            },
            'clustername':'clusterhub',
            'compliant':'NonCompliant'
          }
        }
      }
    },
    '__typename':'ClusterInfo',
    'subItems':[
      {
        'id':'nginx-pod',
        'cells':[
          'nginx-pod',
          '-',
          '-'
        ]
      }
    ]
  }
]

export const clusterSubResourceListTestingResourceData = {
  'headerRows':[
    '',
    'table.header.policy.name',
    'table.header.rule.violation',
    'table.header.control'
  ],
  'subHeaders':[
    'table.header.name',
    'table.header.message',
    'table.header.reason'
  ],
  'rows':[
    {
      'cells':[
        {
          'resourceKey':'metadata.name'
        },
        {
          'resourceKey':'violatedNum'
        },
        {
          'resourceKey':'metadata.annotations["policy.mcm.ibm.com/controls"]'
        }
      ]
    }
  ]
}

export const clusterSubResourceListTestingItemData = [
  {
    'cluster':null,
    'metadata':{
      'name':'policy-ma',
      'namespace':'clusterhub',
      'selfLink':'/apis/policy.mcm.ibm.com/v1alpha1/namespaces/clusterhub/policies/policy-ma',
      'creationTimestamp':'2019-05-28T19:34:14Z',
      'annotations':{
        'policy.mcm.ibm.com/categories':'SystemAndInformationIntegrity',
        'policy.mcm.ibm.com/controls':'MutationAdvisor',
        'policy.mcm.ibm.com/standards':'NIST',
        'seed-generation':'19704'
      },
      'resourceVersion':'1644232',
      'uid':'93182645-817f-11e9-983e-005056a061f1',
      '__typename':'Metadata'
    },
    'status':'Compliant',
    'enforcement':'enforce',
    'detail':{
      'exclude_namespace':[
        '*'
      ],
      'include_namespace':[
        '*'
      ],
      '__typename':'PolicyDetail'
    },
    'raw':{
      'apiVersion':'policy.mcm.ibm.com/v1alpha1',
      'kind':'Policy',
      'metadata':{
        'annotations':{
          'policy.mcm.ibm.com/categories':'SystemAndInformationIntegrity',
          'policy.mcm.ibm.com/controls':'MutationAdvisor',
          'policy.mcm.ibm.com/standards':'NIST',
          'seed-generation':'19704'
        },
        'creationTimestamp':'2019-05-28T19:34:14Z',
        'finalizers':[
          'propagator.finalizer.mcm.ibm.com',
          'policy.finalizer.mcm.ibm.com'
        ],
        'generation':19704,
        'name':'policy-ma',
        'namespace':'clusterhub',
        'ownerReferences':[
          {
            'apiVersion':'policy.mcm.ibm.com/v1alpha1',
            'blockOwnerDeletion':true,
            'controller':true,
            'kind':'Policy',
            'name':'policy-ma',
            'uid':'83e80463-817f-11e9-983e-005056a061f1'
          }
        ],
        'resourceVersion':'1644232',
        'selfLink':'/apis/policy.mcm.ibm.com/v1alpha1/namespaces/clusterhub/policies/policy-ma',
        'uid':'93182645-817f-11e9-983e-005056a061f1'
      },
      'spec':{
        'namespaces':{

        },
        'policy-templates':[
          {
            'objectDefinition':{
              'apiVersion':'policies.ibm.com/v1alpha1',
              'kind':'MutationPolicy',
              'metadata':{
                'label':{
                  'category':'System-Integrity'
                },
                'name':'mutation-policy-example'
              },
              'spec':{
                'conditions':{
                  'ownership':[
                    'ReplicaSet',
                    'Deployment',
                    'DeamonSet',
                    'ReplicationController'
                  ]
                },
                'namespaceSelector':{
                  'exclude':[
                    'kube-system'
                  ],
                  'include':[
                    'default',
                    'kube-*'
                  ]
                },
                'remediationAction':'enforce'
              }
            },
            'status':{
              'Compliant':'Compliant',
              'Validity':{

              },
              'conditions':[
                {
                  'lastTransitionTime':'2019-06-04T17:59:29Z',
                  'message':'Compliant; 0 mutated pods detected in namespace `default`; 0 mutated pods detected in namespace `kube-public`',
                  'reason':'policy: clusterhub/mutation-policy-example',
                  'status':'True',
                  'type':'completed'
                }
              ]
            }
          }
        ],
        'remediationAction':'enforce'
      },
      'status':{
        'compliant':'Compliant'
      }
    },
    '__typename':'Policy',
    'violatedNum':0,
    'subItems':[

    ]
  },
  {
    'cluster':null,
    'metadata':{
      'name':'policy-pod',
      'namespace':'clusterhub',
      'selfLink':'/apis/policy.mcm.ibm.com/v1alpha1/namespaces/clusterhub/policies/policy-pod',
      'creationTimestamp':'2019-05-28T19:33:43Z',
      'annotations':{
        'policy.mcm.ibm.com/categories':'SystemAndCommunicationsProtections,SystemAndInformationIntegrity',
        'policy.mcm.ibm.com/controls':'MutationAdvisor,VA',
        'policy.mcm.ibm.com/standards':'NIST,HIPAA',
        'seed-generation':'183984'
      },
      'resourceVersion':'1674939',
      'uid':'8130d585-817f-11e9-983e-005056a061f1',
      '__typename':'Metadata'
    },
    'status':'NonCompliant',
    'enforcement':'inform',
    'detail':{
      'exclude_namespace':[
        'kube*'
      ],
      'include_namespace':[
        'default'
      ],
      '__typename':'PolicyDetail'
    },
    'raw':{
      'apiVersion':'policy.mcm.ibm.com/v1alpha1',
      'kind':'Policy',
      'metadata':{
        'annotations':{
          'policy.mcm.ibm.com/categories':'SystemAndCommunicationsProtections,SystemAndInformationIntegrity',
          'policy.mcm.ibm.com/controls':'MutationAdvisor,VA',
          'policy.mcm.ibm.com/standards':'NIST,HIPAA',
          'seed-generation':'183984'
        },
        'creationTimestamp':'2019-05-28T19:33:43Z',
        'finalizers':[
          'propagator.finalizer.mcm.ibm.com',
          'policy.finalizer.mcm.ibm.com'
        ],
        'generation':183984,
        'name':'policy-pod',
        'namespace':'clusterhub',
        'ownerReferences':[
          {
            'apiVersion':'policy.mcm.ibm.com/v1alpha1',
            'blockOwnerDeletion':true,
            'controller':true,
            'kind':'Policy',
            'name':'policy-pod',
            'uid':'80fd0634-817f-11e9-983e-005056a061f1'
          }
        ],
        'resourceVersion':'1674939',
        'selfLink':'/apis/policy.mcm.ibm.com/v1alpha1/namespaces/clusterhub/policies/policy-pod',
        'uid':'8130d585-817f-11e9-983e-005056a061f1'
      },
      'spec':{
        'complianceType':'musthave',
        'namespaces':{
          'exclude':[
            'kube*'
          ],
          'include':[
            'default'
          ]
        },
        'object-templates':[
          {
            'complianceType':'musthave',
            'objectDefinition':{
              'apiVersion':'v1',
              'kind':'Pod',
              'metadata':{
                'name':'nginx-pod'
              },
              'spec':{
                'containers':[
                  {
                    'image':'nginx:1.7.9',
                    'name':'nginx',
                    'ports':[
                      {
                        'containerPort':80
                      }
                    ]
                  }
                ]
              }
            },
            'status':{
              'Compliant':'NonCompliant',
              'Validity':{

              },
              'conditions':[
                {
                  'lastTransitionTime':'2019-06-04T21:16:17Z',
                  'message':'pods `nginx-pod` is missing, and should be created',
                  'reason':'K8s missing a must have object',
                  'status':'True',
                  'type':'violation'
                }
              ]
            }
          }
        ],
        'remediationAction':'inform'
      },
      'status':{
        'compliant':'NonCompliant'
      }
    },
    '__typename':'Policy',
    'violatedNum':1,
    'subItems':[
      {
        'id':'nginx-pod',
        'cells':[
          'nginx-pod',
          'pods `nginx-pod` is missing, and should be created',
          'K8s missing a must have object'
        ]
      }
    ]
  },
  {
    'cluster':null,
    'metadata':{
      'name':'policy-role',
      'namespace':'clusterhub',
      'selfLink':'/apis/policy.mcm.ibm.com/v1alpha1/namespaces/clusterhub/policies/policy-role',
      'creationTimestamp':'2019-05-28T19:34:44Z',
      'annotations':{
        'policy.mcm.ibm.com/categories':'SystemAndCommunicationsProtections,SystemAndInformationIntegrity',
        'policy.mcm.ibm.com/controls':'MutationAdvisor,VA',
        'policy.mcm.ibm.com/standards':'NIST,HIPAA',
        'seed-generation':'2'
      },
      'resourceVersion':'41212',
      'uid':'a4ffe7e0-817f-11e9-983e-005056a061f1',
      '__typename':'Metadata'
    },
    'status':'Compliant',
    'enforcement':'enforce',
    'detail':{
      'exclude_namespace':[
        'kube*'
      ],
      'include_namespace':[
        'default'
      ],
      '__typename':'PolicyDetail'
    },
    'raw':{
      'apiVersion':'policy.mcm.ibm.com/v1alpha1',
      'kind':'Policy',
      'metadata':{
        'annotations':{
          'policy.mcm.ibm.com/categories':'SystemAndCommunicationsProtections,SystemAndInformationIntegrity',
          'policy.mcm.ibm.com/controls':'MutationAdvisor,VA',
          'policy.mcm.ibm.com/standards':'NIST,HIPAA',
          'seed-generation':'2'
        },
        'creationTimestamp':'2019-05-28T19:34:44Z',
        'finalizers':[
          'propagator.finalizer.mcm.ibm.com',
          'policy.finalizer.mcm.ibm.com'
        ],
        'generation':2,
        'name':'policy-role',
        'namespace':'clusterhub',
        'ownerReferences':[
          {
            'apiVersion':'policy.mcm.ibm.com/v1alpha1',
            'blockOwnerDeletion':true,
            'controller':true,
            'kind':'Policy',
            'name':'policy-role',
            'uid':'9ff326d4-817f-11e9-983e-005056a061f1'
          }
        ],
        'resourceVersion':'41212',
        'selfLink':'/apis/policy.mcm.ibm.com/v1alpha1/namespaces/clusterhub/policies/policy-role',
        'uid':'a4ffe7e0-817f-11e9-983e-005056a061f1'
      },
      'spec':{
        'namespaces':{
          'exclude':[
            'kube*'
          ],
          'include':[
            'default'
          ]
        },
        'remediationAction':'enforce',
        'role-templates':[
          {
            'apiVersion':'roletemplate.mcm.ibm.com/v1alpha1',
            'complianceType':'musthave',
            'metadata':{
              'creationTimestamp':null,
              'name':'operator-role-policy'
            },
            'rules':[
              {
                'complianceType':'musthave',
                'policyRule':{
                  'apiGroups':[
                    'extensions',
                    'apps'
                  ],
                  'resources':[
                    'deployments'
                  ],
                  'verbs':[
                    'get',
                    'list',
                    'watch',
                    'create',
                    'delete',
                    'patch'
                  ]
                }
              }
            ],
            'selector':{
              'matchLabels':{
                'dev':'true'
              }
            },
            'status':{
              'Compliant':'Compliant',
              'Validity':{
                'valid':true
              },
              'conditions':[
                {
                  'lastTransitionTime':'2019-05-28T19:34:46Z',
                  'message':'k8s RBAC role "operator-role-policy" was missing ',
                  'reason':'K8s RBAC role created',
                  'status':'True',
                  'type':'completed'
                }
              ]
            }
          }
        ]
      },
      'status':{
        'compliant':'Compliant',
        'valid':true
      }
    },
    '__typename':'Policy',
    'violatedNum':0,
    'subItems':[
      {
        'id':'operator-role-policy',
        'cells':[
          'operator-role-policy',
          'k8s RBAC role "operator-role-policy" was missing ',
          'K8s RBAC role created'
        ]
      }
    ]
  }
]
